# Generated by Django 4.2.7 on 2025-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Ctegorta nomi')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Ctegorta slugi')),
                ('is_menu', models.BooleanField(default=True)),
            ],
        ),
    ]
