# Generated by Django 4.2.7 on 2025-08-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=56)),
                ('phone', models.CharField(max_length=56)),
                ('xabar', models.TextField()),
                ('is_trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('image1', models.ImageField(upload_to='news/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('tags', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('post', models.DateTimeField(auto_now_add=True)),
                ('is_sub', models.BooleanField(default=False)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.new')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='core.comment')),
            ],
        ),
    ]
