# Generated by Django 4.2.7 on 2025-08-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_subscribe_new_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '3. Izoh', 'verbose_name_plural': '3. Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '5. Aloqa', 'verbose_name_plural': '5. Aloqalar'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': '2. Yangi', 'verbose_name_plural': '2. Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': '4. Obuna', 'verbose_name_plural': '4. Obunalar'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='xabar',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='create',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='image1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='image2',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='new',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='new',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='new',
            name='views',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='desc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.CharField(default=1, max_length=152),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='view',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_trash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
