# Generated by Django 4.2.7 on 2025-08-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Toifa', 'verbose_name_plural': '1-Toifalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Fkir', 'verbose_name_plural': '3-Fkirlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': '4-Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': '2-Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Obuna', 'verbose_name_plural': '4-Obunalar'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_menu',
            new_name='is_menyu',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.new'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=56),
        ),
    ]
