# Generated by Django 4.2.7 on 2025-08-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='tag',
            new_name='tags',
        ),
    ]
